name: GdUnit4 Test Adapter Bug Report
description: Report a GdUnit4 bug related to the Test Adapter
title: 'GD-XXX: Describe the issue briefly'
labels: ['bug', 'gdunit4.test.adapter']
assignees:
  - MikeSchulze

body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking your time to fill out this bug report!
        - Please search [open](https://github.com/MikeSchulze/gdUnit4Net/issues?q=is%3Aissue) for existing issues for potential duplicates before submit yours.
        - Verify that you are using a [supported Godot version](https://docs.godotengine.org/en/stable/about/release_policy.html). Please always check if your issue is reproducible in the latest version – it may already have been fixed!

  - type: dropdown
    id: gdunit4-api-version
    attributes:
      label: The used Test Adapter version
      description: Which **gdunit4.test.adapter** version are you using?
      options:
        - dev (master branch, development)
        - 3.0.0 (latest release)
        - 2.0.0
        - 1.2.0
        - 1.1.1
        - 1.1.0
        - 1.0.0
      default: 1
    validations:
      required: true

  - type: input
    id: godot-version
    attributes:
      label: The used Godot version
      description: Which Godot version are you using?
      placeholder: v4.2.1.stable.mono.official [b09f793f5]
    validations:
      required: true

  - type: textarea
    id: system
    attributes:
      label: Operating System
      description: |
        What operating system are you using?
        - Specify the OS version, and when relevant hardware information.
      placeholder: 'Example: macOS Big Sur'
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        Describe what you expected to happen and what actually happened.
        Include any specific details, configuration, or environment necessary to reproduce the problem.
        You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Provide a detailed list of steps or sample code that reproduces the issue.
        Having reproducible issues is crucial for contributors to be able to solve them.
        If applicable, include information such as input data, specific configurations, or screenshots.
      placeholder: Describe the steps to reproduce the issue.
      value: |
        Example:
        1. Create a test like described below
        2. Use the Test Explorer and check the listed tests
        The name is not displayed as configured, it shows `MyTest` and should show `BugedName`

        If the issue involves code, please include relevant snippets below:

        ```c#
        namespace Examples;

        using GdUnit4;
        using static GdUnit4.Assertions;

        [TestSuite]
        public class ExampleTest
        {
            // the custom test name is not shown in the test adapter
            [TestCase(TestName='BugedName')]
            public void MyTest()
            {
                AssertThat(true).IsTrue();
            }
        }
        ```

  - type: textarea
    id: example-project
    attributes:
      label: Minimal reproduction project
      description: |
        A small project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
      placeholder: |
        Drag and drop a ZIP archive to upload it (max 10 MB).
        **Do not select another field until the project is done uploading.**
    validations:
      required: false
