name: 'upload test report'
description: 'Uploads the GdUnit test reports'

inputs:
  report-name:
    description: 'Name of the report to be upload.'
    required: true

runs:
  using: composite
  steps:
    - name: 'Upload Test Artifacts'
      uses: actions/upload-artifact@v4
      with:
        retention-days: 10
        name: artifact_${{ inputs.report-name }}
        path: |
          ./test/TestResults/**
          ./test/reports/**
          ./example/TestResults/**
          ./example/reports/**
          /var/lib/systemd/coredump/**
          /var/log/syslog
