name: publish-test-report
description: "Publishes the GdUnit test results"

inputs:
  report-name:
    description: "Name of the check run which will be created."
    required: true

runs:
  using: composite
  steps:
    - name: "Publish Test Results"
      uses: dorny/test-reporter@v1.8.0
      with:
        name: ${{ inputs.report-name }}
        path: "./test/TestResults/test-result.trx"
        reporter: dotnet-trx
        fail-on-error: "false"
        fail-on-empty: "false"
